=== chorman0773/rust-lang-spec/tools/schema/chapter.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="basic-ident">
    <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z][a-zA-Z0-9_]*"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="section-id">
    <xs:restriction base="xs:string">
        <xs:pattern value="[a-z][a-z0-9\-]* (\. [a-z][a-z0-9\-]*)*"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="bnf-ref">
    <xs:restriction base="xs:string">
        <xs:pattern value="[a-z][a-z0-9\-]*"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="rust-edition">
    <xs:restriction base="xs:number">
        <xs:minInclusive value="2015"/>
        <xs:maxExclusive value="2100"/> <!-- TODO: If we ever need to for some reason, bump this number-->
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="rust-version">
    <xs:restriction base="xs:string">
        <xs:pattern value="1\.[0-9]+"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="note-style">
    <xs:restriction base="xs:string">
        <xs:enumeration value="example"/>
        <xs:enumeration value="explanation"/>
        <xs:enumeration value="important"/>
    </xs:restriction>
</xs:simpleType>

<xs:group name="inline-text">
    <xs:choice>
        <xs:element name="b" type="text"/>
        <xs:element name="i" type="text"/>
        <xs:element name="em" type="text"/>
        <xs:element name="code" type="text">
            <xs:attribute name="syntax" type="bnf-ref"/>
        </xs:element>
        <xs:element name="ref" type="section-id"/>
    </xs:choice>
</xs:group>

<xs:attributeGroup name="note-since-spec">
    <xs:choice>
        <xs:attribute name="edition" type="rust-edition"/>
        <xs:attribute name="version" type="rust-version"/>
        <xs:all>
            <xs:attribute name="edition" type="rust-edition"/>
            <xs:attribute name="version" type="rust-version"/>
        </xs:all>
    </xs:choice>
</xs:attributeGroup>

<xs:group name="style">
    <xs:choice>
        <xs:element name="key" type="section-id"/>
        <xs:element name="note">
            <xs:complexType>
                <xs:attribute name="style" type="note-style"/>
            </xs:complexType>
        </xs:element>
        <xs:element name="note-since">
            <xs:complexType>
                <xs:attribute name="style" type="note-style"/>
                <xs:attributeGroup ref="note-since-spec"/>
            </xs:complexType>
        </xs:element>
    </xs:choice>
</xs:group>

<xs:complexType name="text" mixed="true">
    <xs:sequence>
        <xs:group ref="inline-text" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>


<xs:element name="chapter">
    <xs:complexType>
        <xs:attribute name="id" type="section-id" use="required"/>

        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="clause" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id" type="section-id" use="required"/>
                    <xs:choice>
                        <xs:element name="syntax">
                            <xs:complexType>
                                <xs:attribute name="path" value="xs:string"/>
                            </xs:complexType>
                        </xs:element>
                        <xs:sequence>
                            <xs:group ref="style" minOccurs="0"/>
                            <xs:group ref="inline-text"/>
                        </xs:sequence>
                    </xs:choice>
                <xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== chorman0773/rust-lang-spec/spec/lang/exprs/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<chapter id="exprs.index" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://gist.githubusercontent.com/chorman0773/9a4473e9a49466170d1d3a2901fd4f92/raw/cc2959abd7f54f53f5e50b57d9443c7b06448c1f/chapter.xsd">
    <clause id="exprs.index.syntax">
        <key>Syntax</key>
        <syntax ref="index.abnf"/>
    </clause>
    <clause id="exprs.index.constraints">
        <key>Constraints</key>
        Given the index-expr <code syntax="index-expr">base[idx]</code>, 
            either <code syntax="expr">base</code> shall be an expression of an array or slice type and <code syntax="expr">idx</code> shall be an expression of type <code>usize</code>,
            or <code syntax="expr">base</code> shall be of a type <code syntax="type">T</code> and <code syntax="expr">idx</code> shall be of a type <code syntax="type">U</code>,
            such that <code syntax="where-constraint">T: core::ops::Index&lt;U&gt;</code>
    </clause>
    <clause id="exprs.index.panics-array">
        <key>Panics</key>
        If <code syntax="expr">base</code> is of an array type <code syntax="array-type">[T;N]</code>, and <code syntax="expr">idx</code> is of type <code>usize</code>,
        panics unless <code syntax="expr">idx &lt; N</code>. 
        If <code syntax="expr">base</code> is of a slice type <code syntax="slice-type">[T]</code>, and <code syntax="expr">idx</code> is of type <code>usize</code>,
        panics unless <code syntax="expr"> idx &lt; base.len()</code>
    </clause>
    <clause id="exprs.index.pre-array">
        <key>Preconditions</key>
        If <code syntax="expr">base</code> is of an array or slice type, and <code syntax="expr">idx</code> is of type <code>usize</code>,
        then the projection to the <code>idx</code> element of that array or slice at the place denoted by <code>base</code> shall be inbounds of that allocation.
    </clause>
    <clause id="exprs.index.effects-general">
        <key>Effects</key>
        The index-expr <code syntax="index-expr">base[idx]</code> access element <code syntax="expr">idx</code> of the array or container type <code syntax="expr">base</code>.
        Deref coercions are applied to <code syntax="expr">base</code> (<ref>coercions.deref</ref>).
    </clause>
    <clause id="exprs.index.array">
        <key>Effects</key>
        If <code syntax="expr">base</code> is of an array or slice type, and <code syntax="expr">idx</code> is of type <code>usize</code>, 
        then the result is a place that denotes the <code syntax="expr">idx</code> element of the array or slice <code syntax="expr">base</code>
    </clause>
    <clause id="exprs.index.array-note">
        <note style="explanation"/>
        Arrays are indexed from <code>0</code>, so the first element of the array is index <code>0</code>, the second index <code>1</code>, etc. 
        The index <code>N</code> is out of bounds for an array of length <code>N</code>
    </clause>
    <clause id="exprs.index.other">
        If <code syntax="expr">base</code> is not of an array or slice type, or <code syntax="expr">idx</code> is not of type <code>usize</code>, 
        then the expression is an *equivalent-expression* to either <code syntax="expr">*(&lt;T as core::ops::Index::&lt;U&gt;&gt;::index(&amp;base,idx))</code> 
        or <code syntax="expr">*(&lt;T as core::ops::IndexMut::&lt;U&gt;&gt;::index_mut(&amp; mut base,idx))</code>. 
    </clause>
    <clause id="exprs.index.other-note-slice">
        <note style="explanation"/>
        The type <code type="slice-type">[T]</code> implements both the <code syntax="type">core::ops::Index&lt;U&gt;</code> and <code syntax="type">core::ops::IndexMut&lt;U&gt;</code> trait when <code syntax="type">U</code> is a builtin-range type. 
        The behaviour of these trait implementations are described in the library specification and are not documented here. 
        Additionally the type <code type="slice-type">[T]</code> implements both the <code syntax="type">core::ops::Index&lt;usize&gt;</code> and <code syntax="type">core::ops::IndexMut&lt;usize&gt;</code> traits. 
        The behaviour of these impls is to perform the operation described in <ref>exprs.index.array</ref>. 
        These impls are not used by an index-expr if base and idx are both mono known to be an array or slice type and usize respectively. 
    </clause>
    <clause id="exprs.index.mut">
        If the resulting place of the index-expr is (potentially as a subexpression of an index-expr, field-access-expr, or method-invocation-expr) the target of an assignment-expr, or a mutable borrow-expr, 
         the result is given by the call to <code syntax="expr">&lt;T as core::ops::IndexMut::&lt;U&gt;&gt;::index_mut</code>. Otherwise, it is given by the call to <code syntax="expr">&lt;T as core::ops::Index::&lt;U&gt;&gt;::index</code>.
    </clause>
    <clause id="exprs.index.kind">
        Given the index-expr <code syntax="index-expr">base[idx]</code>, <code syntax="expr">base</code> is a place expression, <code syntax="expr">idx</code> is a value expression, and the resulting expression is a place expression.
        The resulting place of an index-expr is mutable if <code syntax="expr">base</code> is mutable. The resulting place is not movable. 
    </clause>
    <clause id="exprs.index.const">
        If <code syntax="expr">base</code> is of an array or slice type, and <code syntax="expr">idx</code> is of type <code>usize</code>, 
        then <code syntax="index-expr">base[idx]</code> is a *constant expression* if <code syntax="expr">base</code> and <code syntax="expr">idx</code> are both *constant expressions*.
    </clause>
</chapter>

=== chorman0773/rust-lang-spec/spec/lang/types/array.xml
<?xml version="1.0" encoding="UTF-8"?>
<chapter id="primitives.array" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://gist.githubusercontent.com/chorman0773/9a4473e9a49466170d1d3a2901fd4f92/raw/cc2959abd7f54f53f5e50b57d9443c7b06448c1f/chapter.xsd">
    <title>Array Type</title>
    <clause id="primitives.array.syntax">
        <key>Syntax</key>
        <syntax ref="array.abnf"/>
    </clause>
    <clause id="primitives.array.constraints">
        <key>Constraints</key>
        Given the array-type <code syntax="array-type">[T;N]</code> and a slice-type <code syntax="slice-type">[T]</code>, <code>N</code> shall be a 
            <i>potentially-dependant constant expression</i> of type <code>usize</code>, and <code>T: core::marker::Sized</code> <ref>traits.sized</ref>.
    </clause>
    <clause id="primitives.array.type">
        An array type, declared <code syntax="array-type">[T;N]</code>, is a special compound type, dependant on <code>T</code>. It has <code>N</code> values of type <code>T</code>
        laid out contiguously in increasing order.
    </clause>
    <clause id="primitives.array.static-size">
        An array <code syntax="array-type">[T;N]</code> is a <i>statically-sized type</i> (<ref>types.sized.static-size</ref>),
        regardless of <code>N</code> or <code>T</code>. <code>T</code> shall be a <i>statically-sized type</i>. 
        The alignment requirement of <code syntax="array-type">[T;N]</code> is the alignment requirement of <code>T</code>, 
        and the size of <code syntax="array-type">[T;N]</code> is <code>N</code> times the size of <code>T</code>.
    </clause>
    <clause id="primitives.slice.type">
        A slice type, declared <code syntax="slice-type">[T]</code>, is a special compound type, dependent on <code>T</code>. 
        It has a statically unknown number of values of <code>T</code> laid out contiguously in increasing order.
    </clause>
    <clause id="primitives.slice.unsized">
        A slice type <code syntax="slice-type">[T]</code>, is a <i>statically-unsized type</i> (<ref>types.sized.static-unsize</ref>). <code>T</code> shall be a <i>statically-sized type</i>.
        The alignment requirement of <code syntax="slice-type">[T]</code> is the alignment requirement of <code>T</code>
    </clause>
    <clause id="primitives.slice.meta">
        The metadata of the slice type <code syntax="slice-type">[T]</code> is <code>usize</code>, regardless of <code>T</code>. The metadata value stores the number of elements of the slice.
        The size of a value of type <code syntax="slice-type">[T]</code>, given the metadata value is <code>N</code>, is <code>N</code> times the size of <code>T</code>.
    </clause>
    <clause id="primitives.slice.unsize">
        An array type <code syntax="array-type">[T;N]</code> unsizes to the slice type <code syntax="slice-type">[T]</code> (<ref>exprs.unsize</ref>). 
        The metadata for the coercion is the value <code>N</code> (<ref>exprs.unsize.metadata</ref>).
    </clause>
</chapter>

=== chorman0773/rust-lang-spec/spec/lang/exprs/array.xml
<?xml version="1.0" encoding="UTF-8"?>
<chapter id="exprs.array" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://gist.githubusercontent.com/chorman0773/9a4473e9a49466170d1d3a2901fd4f92/raw/cc2959abd7f54f53f5e50b57d9443c7b06448c1f/chapter.xsd">
    <title>Array Construction</title>
    <clause id="exprs.array.syntax">
        <key>Syntax</key>
        <syntax ref="array.abnf"/>
    </clause>
    <clause id="exprs.array.constraints">
        <key>Constraints</key>
        Given the array-expr <code syntax="array-expr">[E0,E1, .., En]</code>, <code>n</code> shall be representible as a value of type <code>usize</code>,
        and each <code syntax="expr">Ei</code> for <code>0&lt;=i&lt;n</code> shall, after implicit coercions, be of the same type<code syntax="type">T</code>, such that <code syntax="where-constraint">T: core::marker::Sized</code>.
    </clause>
    <clause id="exprs.array.mandates">
        <key>Mandates</key>
        Given the array-expr <code syntax="array-expr">[E0,E1, .., En]</code> where each <code syntax="expr">Ei</code> is of type <code syntax="type">T</code>, 
        <code syntax="expr">size_of::&lt;T&gt;() * n</code> shall be representible as a value of type <code>isize</code>.
    </clause>
    <clause id="exprs.arrays.mandates-note">
        <note style="explanation"/>
        The latter constraint means that the effectively largest <code>n</code> 
    </clause>
    <clause id="exprs.array.effects">
        <key>Effects</key>
        The array-expr <code syntax="array-expr">[E0,E1, .., En]</code> constructs the <code>n</code> element array of type <code syntax="type">T</code>,
        such that the <code>i</code>th element of the resulting array is equivalent to <code syntax="expr">Ei</code> for <code>0&lt;=i&lt;n</code> (<ref>exprs.index.array</ref>).
    </clause>
    <clause id="exprs.arrays.type-kind">
        Given the array-expr <code syntax="array-expr">[E0,E1, .., En]</code>, each <code syntax="expr">Ei</code> for <code>0&lt;=i&lt;n</code> is a value expression (<ref>exprs.kind.value</ref>), 
        and the array-expr is a value expression. The type of the resulting array-expr is the array-type <code syntax="array-type">[T;n]</code> (<ref>primitives.arrays</ref>).
    </clause>
    <clause id="exprs.arrays.const">
        If all of <code>E0, E1, .., En</code> are <i>constant expressions</i> (<ref>exprs.const</ref>), then <code syntax="array-expr">[E0,E1, .., En]</code> is a <i>constant expression</i>
    </clause>
    <clause id="exprs.repeat.syntax">
        <key>Syntax</key>
        <syntax ref="repeat.abnf"/>
    </clause>
    <clause id="exprs.repeat.constraints">
        <key>Constraints</key>
        Given the repeat-expr <code syntax="repeat-expr">[val ; N]</code>, <code syntax="expr">N</code> shall be a <i>potentially-dependant</i> constant expression of <code>usize</code>,
        and <code syntax="expr">val</code>. If <code syntax="expr">N</code> is a *dependent constant expression* or <code>N &gt; 2</code>, 
        then either <code syntax="where-constraint">T: core::marker::Copy</code> or <code syntax="expr">val</code> shall be a (potentially parenthesized) path-expr that denotes a const item.
    </clause>
    <clause id="exprs.repeat.mandates">
        <key>Mandates</key>
        Given the repeat-expr <code syntax="repeat-expr">[val ; N]</code>, where <code syntax="expr">val</code> is of type <code syntax="type">T</code>, 
        <code syntax="expr">size_of::&lt;T&gt;() * N</code>
    </clause>
    <clause id="exprs.repeat.effects">
        <key>Effects</key>
        The repeat-expr <code syntax="repeat-expr">[val ; N]</code> constructs the <code syntax="expr">N</code> element array of type <code syntax="type">T</code>, 
        such that the <code>i</code>th element of the resulting array is equivalent to <code syntax="expr">val</code> for <code>0&lt;=i&lt;N</code> (<ref>exprs.index.array</ref>). 
    </clause>
    <clause id="exprs.repeat.const-item">
        If <code syntax="expr">val</code> is a (potentially-parenthesized) path-expr that denotes a const item (<ref>items.const</ref>) or an associated const (<ref>items.associated-const</ref>),
        then <code syntax="expr">val</code> is evaluated <code syntax="expr">N</code> times, such that the <code>i</code>th evaluation initializes the <code>i</code>th element of the array.
    </clause>
    <clause id="exprs.repeat.const-item.note">
        <note style="explanation"/>
        If <code syntax="expr">N</code> is <code>0</code>, then <code syntax="expr">val</code> is not evaluated. 
    </clause>
    <clause id="exprs.repeat.copy">
        If <code syntax="expr">val</code> is not a (potentially-parenthesized) path-expr that denotes a const item or an associated const,
        then <code syntax="expr">val</code> is evaluated exactly once. If <code syntax="expr">N</code> is <code>0</code>, then the result of evaluating <code syntax="expr">val</code> is dropped.
        Otherwise, the result of <code syntax="expr">val</code> is copied to each element of the array.
    </clause>
    <clause id="exprs.repeat.copy-note">
        <note style="explanation"/>
        If <code syntax="expr">N</code> is <code>1</code>, then <code syntax="expr">val</code> is not copied.
    </clause>
    <clause id="exprs.repeat.copy-since">
        <note-since style="important" version="1.63"/>
        Prior to Rust 1.63, if <code syntax="expr">N</code> is <code>0</code>, then the result of <code syntax="expr">val</code> was forgetten instead.
    </clause>
    <clause id="exprs.repeat.type-kind">
        Given the repeat-expr <code syntax="repeat-expr">[val;N]</code>, <code syntax="expr">val</code> is a value expression, and the resulting repeat-expr is a value expression.
        The type of the repeat-expr is <code syntax="array-expr">[T;N]</code>.
    </clause>
    <clause id="exprs.repeat.const">
        If <code syntax="expr">val</code> is a *constant expression*, then <code syntax="repeat-expr">[val;N]</code> is a *constant expression*.
    </clause>
</chapter>
